actions:
  - src/actions/**/*
channels:
  - '**/?(*Channel*).ts'
client:
  - src/client/Client.ts
dependecies:
  - package.json
  - package-lock.json
examples:
  - examples/**/*
exports:
  - src/index.ts
github:
  - .github/**/*
intents:
  - src/utils/Intents.ts
  - src/constants/intents.ts
managers:
  - src/managers/**/*
permissions:
  - src/utils/Permission.ts
  - src/constants/permissions.ts
roles:
  - '**/?(*Role*).ts'
structures:
  - src/structures/**/*
utility:
  - src/utils/**/*
websocket:
  - src/client/websocket/**/*
